#!/bin/bash

source_dir="files"
destination_dir="."

for file in "$source_dir"/*; do
    
        first_letter=$(basename "$file" | cut -c1 | tr '[:upper:]' '[:lower:]')
        if [ -d "$destination_dir/$first_letter" ]; then
            mv "$file" "$destination_dir/$first_letter/"
        fi
    
done